# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QInputDialog

from BIBLIOTECAS.Basicas.matplolib.graf.MplCanvas import MplCanvas
from BIBLIOTECAS.Basicas.matplolib.graf.graf import Ui_Graf


class Ui_MainWindow(QtWidgets.QDialog):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(455, 270)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 70, 99, 27))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 455, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.acciones()

    def acciones(self):
        self.pushButton.clicked.connect(self.ventana)

    def ventana(self):
        consulta = QWidget()
        items = ("sencillo","doble")
        seleccion, accion = QInputDialog.getItem(consulta,"Graficos","Seleccione el grafico",items)
        vent = Ui_Graf()
        if accion:
            if seleccion == "sencillo" :
                data = ([0,1,2,3,4], [10,1,20,3,40])
                vent.setupUi(data, "sencillo")
                rest = vent.exec_()
            elif seleccion == "doble":
                x = np.arange(100)
                y = np.exp(np.linspace(0, 5, 100))
                data = (x,y)
                vent.setupUi(data,"doble" )
                rest = vent.exec_()
        if rest :
            print("ok")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Genera Graf"))


