# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget, QInputDialog

#-------------
from PyQt5.QtWidgets import*
from PyQt5.uic import loadUi
from matplotlib.backends.backend_qt5agg import (NavigationToolbar2QT as NavigationToolbar)
import os

import numpy as np
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(490, 373)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_genera = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_genera.setGeometry(QtCore.QRect(160, 110, 141, 51))
        self.pushButton_genera.setObjectName("pushButton_genera")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 490, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.acciones()

    def acciones(self):
        self.pushButton_genera.clicked.connect(self.ventana)

    def ventana(self):
        consulta = QWidget()
        items = ("sencillo", "doble")
        seleccion, accion = QInputDialog.getItem(consulta, "Graficos", "Seleccione el grafico", items)

        self.vent = QDialog()
        ruta = os.getcwd()
        total = ruta +"/graf2/graf2.ui"
        loadUi(total, self.vent)
        self.vent.setWindowTitle("PyQt5 & Matplotlib Example GUI")
        self.vent.pushButton_generar.clicked.connect(self.update_graph)
        self.vent.addToolBar(NavigationToolbar(self.MplWidget.canvas, self))

    def update_graph(self):
        fs = 500
        f = random.randint(1, 100)
        ts = 1 / fs
        length_of_signal = 100
        t = np.linspace(0, 1, length_of_signal)

        cosinus_signal = np.cos(2 * np.pi * f * t)
        sinus_signal = np.sin(2 * np.pi * f * t)

        self.vent.MplWidget.canvas.axes.clear()
        self.vent.MplWidget.canvas.axes.plot(t, cosinus_signal)
        self.vent.MplWidget.canvas.axes.plot(t, sinus_signal)
        self.vent.MplWidget.canvas.axes.legend(('cosinus', 'sinus'), loc='upper right')
        self.vent.MplWidget.canvas.axes.set_title('Cosinus - Sinus Signal')
        self.vent.MplWidget.canvas.draw()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_genera.setText(_translate("MainWindow", "Generar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
